name: audioflow2mqtt
description: Audioflow speaker switch to MQTT gateway
version: "0.8.0"
slug: audioflow2mqtt
init: false
arch:
- amd64
- aarch64
- armv7
discovery:
- mqtt
services:
- mqtt:need
hassio_api: true
host_network: true
url: https://github.com/henrycarteruk/audioflow2mqtt-addon

options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  qos: 1
  base_topic: audioflow2mqtt
  devices: []
  log_level: info

schema:
  mqtt_host: str?
  mqtt_port: int?
  mqtt_user: str?
  mqtt_pass: password?
  qos: int(0,2)?
  base_topic: str
  devices:
  - str?
  - str?
  - str?
  - str?
  - str?
  log_level: list(debug|info|warning|error)
